kind: List
apiVersion: v1
metadata:
  name: image-streams
  annotations:
    description: ImageStream definition for Red Hat Interconnect 1.x
    openshift.io/provider-display-name: Red Hat, Inc.
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: interconnect-1
    annotations:
      openshift.io/display-name: Red Hat Interconnect 1.x
      openshift.io/provider-display-name: Red Hat, Inc.
      version: 1.4.10
  labels:
    xpaas: 1.4.10
  spec:
    tags:
    - name: '1.1'
      annotations:
        description: Red Hat Interconnect 1.1 router image.
        iconClass: icon-amq
        tags: messaging,amq,jboss
        supports: interconnect:1.1,messaging
        version: '1.1'
        openshift.io/display-name: Red Hat Interconnect 1.1
      from:
        kind: DockerImage
        name: amq-interconnect-1/amq-interconnect-1-openshift:1.1
