kind: Template
apiVersion: v1
metadata:
  name: amq-interconnect-1-basic
  annotations:
    description: Application template for Red Hat Interconnect Router.
    iconClass: icon-amq
    openshift.io/provider-display-name: Red Hat, Inc.
    tags: messaging,amq,jboss,hidden
    version: 1.4.10
    openshift.io/display-name: Red Hat Interconnect Router 1.x
labels:
  template: amq-interconnect-1-basic
  xpaas: 1.4.10
message: A new messaging service has been created in your project.
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: router
  required: true
- displayName: ImageStream Namespace
  description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  value: openshift
- displayName: qdrouterd.conf
  description: The router configuration file
  name: QDROUTERD_CONF
  value: |-
    router {
        mode: interior
        id: ${HOSTNAME}
    }

    listener {
        host: 0.0.0.0
        port: amqp
        authenticatePeer: no
        saslMechanisms: ANONYMOUS
    }

    address {
        prefix: closest
        distribution: closest
    }

    address {
        prefix: multicast
        distribution: multicast
    }

    address {
        prefix: unicast
        distribution: closest
    }

    address {
        prefix: exclusive
        distribution: closest
    }

    address {
        prefix: broadcast
        distribution: multicast
    }
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}-amqp
    labels:
      application: ${APPLICATION_NAME}
    annotations:
      description: The router's AMQP port.
  spec:
    ports:
    - port: 5672
      targetPort: 5672
    selector:
      deploymentConfig: ${APPLICATION_NAME}-amq
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}-http
    labels:
      application: ${APPLICATION_NAME}
    annotations:
      description: The router's http port.
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}-amq
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-amq"
    labels:
      application: "${APPLICATION_NAME}"
  spec:
    strategy:
      type: Rolling
      rollingParams:
        maxSurge: 0
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}-amq"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_STREAM_NAMESPACE}"
          name: amq-interconnect-1-openshift:latest
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentConfig: "${APPLICATION_NAME}-amq"
    template:
      metadata:
        name: "${APPLICATION_NAME}-amq"
        labels:
          deploymentConfig: "${APPLICATION_NAME}-amq"
          application: "${APPLICATION_NAME}"
      spec:
        terminationGracePeriodSeconds: 60
        containers:
        - name: "${APPLICATION_NAME}-amq"
          ports: 
          - name: amqp
            containerPort: 5672
            protocol: TCP
          - name: http
            containerPort: 8080
            protocol: TCP
          env:
          - name: QDROUTERD_CONF
            value: "${QDROUTERD_CONF}"
            image: amq-interconnect-1-openshift:latest
          volumeMounts:
          - name: config-volume
            mountPath: /opt/interconnect/etc/configmap/
          terminationGracePeriodSeconds: 60
        volumes:
        - name: config-volume
          configMap:
            name: configmap
        imagePullPolicy: Always
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: configmap
  data:
    qdrouterd.conf: ${QDROUTERD_CONF}
